version: '3.7'

services:
  web:
    build: ./app
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - static_volume:/app/staticfiles
    env_file:
      - ./.env

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  static_volume: