version: '3.7'

services:
  web:
    env_file: ./.env
    build: ./app
    image: raysandeep/knockouts
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    deploy:
      mode: replicated
      replicas: 4
      restart_policy:
        condition: any
    labels:
      - traefik.backend=web
      - traefik.frontend.rule=Host:api.knockouts.dscvit.com;PathPrefix:/api
      - traefik.docker.network=web
      - traefik.port=8000
    networks:
      - internal
      - web
    volumes:
      - static_volume:/app/staticfiles
    

  web1:
    build: ./app1
    image: raysandeep/knockouts1
    command: uvicorn main:app --host 0.0.0.0 --port 5000 --reload
    ports:
      - 5000:5000
    deploy:
      mode: replicated
      replicas: 4
      restart_policy:
        condition: any
    volumes:
      - static_volume:/app/staticfiles
    labels:
      - traefik.backend=web1
      - traefik.frontend.rule=Host:api.knockouts.dscvit.com;PathPrefix:/api1
      - traefik.docker.network=web
      - traefik.port=5000
    networks:
      - internal
      - web
    env_file:
      - .env

  traefik:
    image: traefik:1.7.2-alpine
    restart: always
    container_name: traefik
    networks:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    labels:
      - traefik.frontend.rule=Host:api.knockouts.dscvit.com
      - traefik.port=8080
  
volumes:
  static_volume:

networks:
  web:
    external: true
  internal:
    external: false