defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.dashboard]
    address = ":8080"
    [entryPoints.dashboard.auth]
      [entryPoints.dashboard.auth.basic]
        users = ["admin:$apr1$V0N2rFSc$WyGoPftn1sYrKtoEB0tOQ0"]

  [entryPoints.http]
    address = ":80"
      [entryPoints.http.redirect]
        entryPoint = "https"
  [entryPoints.https]
    address = ":443"
      [entryPoints.https.tls]

[tracing]
  serviceName = "traefik"

[metrics]
  [metrics.influxDB]
    address = "localhost:8089"
    database = "influxdb"
    username = "sandeep"
    password = "abhis@123"
    addServicesLabels = true

[api]
entrypoint="dashboard"

[acme]
email = "rayanuthalas@gmail.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
  [acme.httpChallenge]
  entryPoint = "http"

[docker]
domain = "api.knockouts.dscvit.com"
watch = true
network = "web"