# Generated by Django 3.0.8 on 2020-07-16 18:37

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('question_title', models.CharField(max_length=200)),
                ('question', django.contrib.postgres.fields.jsonb.JSONField(default={'blocks': [{'data': {'level': 1, 'text': 'Dinner Rush'}, 'type': 'header'}, {'data': {'level': 2, 'text': 'Problem Description'}, 'type': 'header'}, {'data': {'text': 'It is another night at the Darling Canteen and a huge queue of people are waiting for their turn to get a table. The customers are given token numbers as soon as they add their names to the waiting list. The token numbers start from 1 and the next person gets the next number i.e. 2 and so on till n if there are n customers.'}, 'type': 'paragraph'}, {'data': {'text': 'Some people are extremely tired of waiting and use bribery to move forward. They can bribe the person waiting in the queue just before them and switch positions with them. They can exchange their positions but the token numbers they have will be the same. A person can bribe maximum of 2 people in order to move forward. For example a person with token 3 can bribe the person with token 2 in order to move forward.'}, 'type': 'paragraph'}, {'data': {'text': 'You see that the queue looks too chaotic as many people are bribing to move forward. Thus you want to find out the minimum number of people who were bribed by looking at the current situation of the queue.'}, 'type': 'paragraph'}, {'data': {'level': 2, 'text': 'Input Format'}, 'type': 'header'}, {'data': {'text': 'Each&nbsp;input&nbsp;consists&nbsp;of&nbsp;two&nbsp;lines'}, 'type': 'paragraph'}, {'data': {'items': ['The first line of input contains the number n - Number of people in the queue', 'The second line of input contains an n token numbers separated by spaces (The current order of the people with tokens)'], 'style': 'ordered'}, 'type': 'list'}, {'data': {'level': 2, 'text': 'Output Format'}, 'type': 'header'}, {'data': {'text': 'Print the minimum number of people who were bribed to attain the current queue. If a person had to bribe more than 2 people to attain the current queue then print -1.'}, 'type': 'paragraph'}, {'data': {'level': 2, 'text': 'Constraints'}, 'type': 'header'}, {'data': {'items': ['1 &lt;= n &lt;= 10^5<br>', 'Token numbers are positive'], 'style': 'ordered'}, 'type': 'list'}, {'data': {'level': 2, 'text': 'Sample Input 1'}, 'type': 'header'}, {'data': {'text': '5'}, 'type': 'paragraph'}, {'data': {'text': '3 1 2 5 4'}, 'type': 'paragraph'}, {'data': {'level': 2, 'text': 'Sample Output 1'}, 'type': 'header'}, {'data': {'text': '3'}, 'type': 'paragraph'}, {'data': {'text': 'Explanation: 3 will bribe 1 and 2. 5 bribed 4.'}, 'type': 'paragraph'}, {'data': {'level': 2, 'text': 'Sample Input 2'}, 'type': 'header'}, {'data': {'text': '8'}, 'type': 'paragraph'}, {'data': {'text': '2 1 3 4 8 5 6 7'}, 'type': 'paragraph'}, {'data': {'level': 2, 'text': 'Sample Output 2'}, 'type': 'header'}, {'data': {'text': '-1'}, 'type': 'paragraph'}, {'data': {'text': 'Explanation: 8 must bribe 5, 6 and 7 to come at the given position. Thus 8 had to bribe more than 2 people. So output is -1.'}, 'type': 'paragraph'}], 'time': 1594920529603, 'version': '2.18.0'})),
                ('is_assigned', models.BooleanField(default=False)),
                ('difficulty_level', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TestCaseHolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('stdin', models.TextField()),
                ('stdout', models.TextField()),
                ('max_time', models.DecimalField(decimal_places=8, max_digits=10)),
                ('max_memory', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_portal.QuestionsModel')),
            ],
        ),
        migrations.CreateModel(
            name='TestCaseSolutionLogger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('stdin', models.TextField(null=True)),
                ('stdout', models.TextField(null=True)),
                ('time', models.DecimalField(decimal_places=8, max_digits=10, null=True)),
                ('memory', models.IntegerField(default=0, null=True)),
                ('error', models.CharField(max_length=500, null=True)),
                ('token', models.CharField(max_length=100)),
                ('is_solved', models.BooleanField(default=False)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_portal.QuestionsModel')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_portal.TestCaseHolder')),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_portal.QuestionsModel')),
            ],
        ),
        migrations.CreateModel(
            name='RoomParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now=True)),
                ('current_code', models.TextField()),
                ('language_of_code', models.CharField(max_length=100)),
                ('is_submitted', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_portal.Rooms')),
            ],
        ),
    ]
