# Generated by Django 3.0.8 on 2020-07-17 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0002_auto_20200717_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rounds',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('round_name', models.CharField(max_length=100)),
                ('difficulty_allowance', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='questionsmodel',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rooms',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_portal.Rounds'),
            preserve_default=False,
        ),
    ]
