# Generated by Django 3.0.8 on 2020-07-20 10:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0006_auto_20200720_1515'),
    ]

    operations = [
        migrations.DeleteModel(
            name='roomparticipantmanager',
        ),
        migrations.CreateModel(
            name='RoomParticipantManager',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now=True)),
                ('current_code', models.TextField()),
                ('language_of_code', models.CharField(max_length=100)),
                ('is_submitted', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('room_seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_portal.RoomParticipantAbstract')),
            ],
        ),
    ]
