# Generated by Django 3.0.8 on 2020-07-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0007_roomparticipantmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcaseholder',
            name='is_sample',
            field=models.BooleanField(default=False),
        ),
    ]
