# Generated by Django 3.0.8 on 2020-07-21 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0008_testcaseholder_is_sample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcasesolutionlogger',
            name='question',
        ),
        migrations.AddField(
            model_name='testcasesolutionlogger',
            name='room_solution',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='admin_portal.RoomParticipantManager'),
            preserve_default=False,
        ),
    ]
