# Generated by Django 3.0.8 on 2020-07-23 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0010_auto_20200722_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcasesolutionlogger',
            name='room_solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_portal.RoomParticipantManager'),
        ),
    ]
