# Generated by Django 3.0.8 on 2020-07-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0012_auto_20200724_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcaseholder',
            name='score',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='testcasesolutionlogger',
            name='score_for_this_testcase',
            field=models.IntegerField(default=0),
        ),
    ]
