# Generated by Django 3.0.8 on 2020-07-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_disqualified',
            field=models.BooleanField(default=False),
        ),
    ]
