# Generated by Django 3.0.8 on 2020-07-16 18:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsmodel',
            name='question',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
