# Generated by Django 3.0.8 on 2020-07-17 06:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0003_auto_20200717_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rounds',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
