# Generated by Django 3.0.8 on 2020-07-17 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_portal', '0004_auto_20200717_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomParticipantAbstract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_portal.Rooms')),
            ],
        ),
        migrations.CreateModel(
            name='RoomParticipantManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now=True)),
                ('current_code', models.TextField()),
                ('language_of_code', models.CharField(max_length=100)),
                ('is_submitted', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('room_seat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_portal.RoomParticipantAbstract')),
            ],
        ),
        migrations.DeleteModel(
            name='RoomParticipant',
        ),
    ]
