# Generated by Django 3.0.8 on 2020-07-20 09:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0005_auto_20200717_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomparticipantmanager',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='roomparticipantmanager',
            name='room_seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_portal.RoomParticipantAbstract'),
        ),
    ]
