# Generated by Django 3.0.8 on 2020-07-21 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0009_auto_20200722_0344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcasesolutionlogger',
            name='participant',
        ),
        migrations.AlterField(
            model_name='testcasesolutionlogger',
            name='room_solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_portal.RoomParticipantAbstract'),
        ),
    ]
